baseurl = "http://umich.edu/~fencing"
languageCode = "en-us"
title = "University of Michigan Fencing Club"
theme = "club-theme"
copyright = "(c) 2019 University of Michigan Fencing Club"

[params]
  noCategoryLink = true
  description = "The top collegiate fencing club in the nation."
  image = "img/2017_CFC_team_with_trophies.png"
  themeColor = "#003e78"

  # Google Calendar ID used to embed agenda in sidebar.
  # If changing this, make sure to update `content/schedule.md` and
  #   `content/add_calendar.md`.
  calendarId = "umich.edu_toeb19ptci3123vprh6464i308@group.calendar.google.com"

  practiceLocation = "the <a href='https://www.google.com/maps/place/University+of+Michigan-Sports+Coliseum/@42.2744305,-83.7456399,16z/data=!4m5!3m4!1s0x883cae3762fe5cc1:0xd3f27cff08a1643f!8m2!3d42.2720542!4d-83.7459577?hl=en' target='_blank'> IM Sports Coliseum</a>"
  
  # No default values
  [params.practiceTimes]
    tuesday = "7-9 pm"
    thursday = "7-9 pm"
    friday = "7-9 pm"

  [params.social]
    facebook = "umichfencing"
    twitter = "um_fencing"
    instagram = "umfencing"
    lightwidget = "6d7ef1a4526055f7872df363b7110a28"
    youtube = "UCLjqnWZsMBiHfeuEXiUSgGQ"
    community = "https://maizepages.umich.edu/organization/fencing"

  [params.sponsor]
	logo = "img/rec-sports-logo.jpg"
	text = "Michigan Rec Sports Logo"
	link = "https://recsports.umich.edu/"
	size = "100px" # Default: 100px

[[menu.main]]
  name = "Roster"
  url = "/roster/"
  weight = "0"

[[menu.main]]
  name = "Schedule"
  url = "/schedule/"
  weight = "1"

[[menu.main]]
  name = "Results"
  url = "/results/"
  weight = "2"

[[menu.main]]
  name = "Join"
  url = "/join/"
  weight = "3"

[[menu.main]]
  name = "About Fencing"
  url = "/about_fencing/"
  weight = "4"

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = "5"

[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = "6"
